// services/ticket.service.js
const QRCode = require("qrcode");
const Ticket = require("../models/ticket.model");
const Event = require("../models/event.model");
const User = require("../models/user.model");
const { sendEmailWithAttachment } = require("../utils/email");
const { generateToken } = require("../utils/crypto");
const path = require("path");
const fs = require("fs");

class TicketService {
  // Generate ticket for a user
  async generateTicket(eventId, userId, options = {}) {
    try {
      const { sendEmail = true, manualApproval = false } = options;

      const event = await Event.findById(eventId);
      if (!event) {
        throw new Error("Event not found");
      }

      const user = await User.findById(userId);
      if (!user) {
        throw new Error("User not found");
      }

      // Check if ticket already exists
      const existingTicket = await Ticket.findOne({ eventId, userId });
      if (existingTicket) {
        return {
          success: true,
          ticket: existingTicket,
          message: "Ticket already exists",
        };
      }

      // Generate ticket token and QR code
      const token = generateToken(32);
      const ticketData = {
        ticketId: token,
        eventId: eventId.toString(),
        userId: userId.toString(),
        type: "event-ticket",
        timestamp: new Date().toISOString()
      };

      const qrContent = JSON.stringify(ticketData);
      const qrCode = await QRCode.toDataURL(qrContent);

      // Create ticket
      const ticket = await Ticket.create({
        eventId,
        userId,
        qrCode,
        token,
        status: manualApproval ? 'pending' : 'active',
        autoGenerated: options.autoGenerated || false,
      });

      // Send email if requested and not manual approval
      if (sendEmail && !manualApproval) {
        await this.sendTicketEmail(ticket, user, event);
      }

      return {
        success: true,
        ticket,
        message: manualApproval ? 
          "Ticket generated and pending approval" : 
          "Ticket generated successfully",
      };
    } catch (error) {
      console.error("Ticket generation error:", error);
      throw error;
    }
  }

  // Send ticket email to user
  async sendTicketEmail(ticket, user, event) {
    try {
      const logoUrl = "https://drive.google.com/file/d/1on6hv6QuNCGumvrtuB96l2XBClD0SKKn/view?usp=drive_link";
      const ticketId = ticket._id.toString();
      
      const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Event Ticket - Team Eklavya</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap');
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: 'Inter', Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f8fafc;
            -webkit-font-smoothing: antialiased;
            -webkit-text-size-adjust: 100%;
        }
        
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            background: #ffffff;
            width: 100%;
        }
        
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 40px 30px;
            text-align: center;
            color: white;
            position: relative;
            overflow: hidden;
        }
        
        
        .logo {
    max-width: 300px;
    height: auto;
    margin: auto;
    display: block;
    margin-top: -7rem;
    margin-bottom: -5rem;
        }
        
        .header h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            text-shadow: 0 2px 4px rgba(0,0,0,0.3);
            line-height: 1.3;
        }
        
        .header p {
            font-size: 16px;
            opacity: 0.95;
            font-weight: 400;
        }
        
        .content {
            padding: 30px 25px;
            background: #f8f9fa;
        }
        
        .ticket-card {
            background: white;
            border-radius: 12px;
            padding: 25px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.08);
            border: 1px solid #e8ecef;
        }
        
        .greeting {
            color: #2E86C1;
            font-size: 22px;
            font-weight: 600;
            margin-bottom: 15px;
        }
        
        .event-details {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 10px;
            margin: 20px 0;
            border-left: 4px solid #2E86C1;
        }
        
        .event-details h3 {
            color: #2c3e50;
            margin-bottom: 12px;
            font-size: 16px;
            font-weight: 600;
        }
        
        .detail-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 8px;
            padding-bottom: 8px;
            border-bottom: 1px solid #e9ecef;
            flex-wrap: wrap;
        }
        
        .detail-row:last-child {
            border-bottom: none;
            margin-bottom: 0;
            padding-bottom: 0;
        }
        
        .detail-label {
            font-weight: 500;
            color: #6c757d;
            flex: 1;
            min-width: 120px;
        }
        
        .detail-value {
            font-weight: 600;
            color: #2c3e50;
            text-align: right;
            flex: 2;
            min-width: 150px;
        }
        
        .qr-section {
            text-align: center;
            margin: 25px 0;
            padding: 20px;
            background: linear-gradient(135deg, #f8f9fa 0%, #e9ecef 100%);
            border-radius: 10px;
            border: 2px dashed #dee2e6;
        }
        
        .qr-code {
            max-width: 180px;
            height: auto;
            border: 3px solid white;
            border-radius: 10px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
        }
        
        .ticket-id {
            background: #2E86C1;
            color: white;
            padding: 10px 16px;
            border-radius: 20px;
            font-weight: 600;
            font-size: 13px;
            letter-spacing: 0.5px;
            margin-top: 12px;
            display: inline-block;
        }
        
        .important-note {
            background: #e8f4fd;
            padding: 16px;
            border-radius: 8px;
            border-left: 4px solid #2E86C1;
            margin: 20px 0;
        }
        
        .important-note p {
            margin: 0;
            color: #2E86C1;
            font-size: 13px;
            font-weight: 500;
            line-height: 1.5;
        }
        
        .footer {
            text-align: center;
            padding: 25px 20px;
            background: #2c3e50;
            color: white;
            border-radius: 0 0 12px 12px;
        }
        
        .social-links {
            display: flex;
            justify-content: center;
            gap: 15px;
            margin: 20px 0;
            flex-wrap: wrap;
        }
        
        .social-link {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            padding: 10px;
            background: rgba(255,255,255,0.1);
            border-radius: 50%;
            transition: all 0.3s ease;
            text-decoration: none;
            width: 44px;
            height: 44px;
        }
        
        .social-icon {
            color: white;
            font-size: 18px;
            font-weight: bold;
            display: inline-block;
            line-height: 1;
        }
        
        .contact-info {
            font-size: 13px;
            opacity: 0.8;
            margin-top: 15px;
            line-height: 1.6;
        }
        
        /* Enhanced Mobile Responsiveness */
        @media (max-width: 600px) {
            .header {
                padding: 30px 20px;
            }
            
            .header h1 {
                font-size: 24px;
            }
            
            .header p {
                font-size: 14px;
            }
            
            .logo {
        max-width: 300px;
        margin-bottom: -5rem;
        margin-top: -6rem;
            }
            
            .content {
                padding: 20px 15px;
            }
            
            .ticket-card {
                padding: 20px 15px;
                border-radius: 10px;
            }
            
            .greeting {
                font-size: 20px;
            }
            
            .event-details {
                padding: 15px;
            }
            
            .detail-row {
                flex-direction: column;
                gap: 4px;
            }
            
            .detail-label,
            .detail-value {
                text-align: left;
                flex: none;
                min-width: auto;
            }
            
            .detail-value {
                font-weight: 600;
            }
            
            .qr-section {
                padding: 15px;
                margin: 20px 0;
            }
            
            .qr-code {
                max-width: 150px;
            }
            
            .social-links {
                gap: 12px;
            }
            
            .social-link {
                width: 40px;
                height: 40px;
                padding: 8px;
            }
            
            .social-icon {
                font-size: 16px;
            }
            
            .footer {
                padding: 20px 15px;
            }
        }
        
        @media (max-width: 400px) {
            .header {
                padding: 25px 15px;
            }
            
            .header h1 {
                font-size: 22px;
            }
            
            .content {
                padding: 15px 10px;
            }
            
            .ticket-card {
                padding: 15px 12px;
            }
            
            .qr-code {
                max-width: 130px;
            }
            
            .social-links {
                gap: 10px;
            }
        }
        
        /* Print Styles */
        @media print {
            .email-container {
                box-shadow: none;
                margin: 0;
            }
            
            .ticket-card {
                box-shadow: none;
                border: 2px solid #333;
            }
            
            .qr-code {
                border: 2px solid #333;
            }
        }
    </style>
</head>
<body>
    <div class="email-container">
        <!-- Header Section -->

        <center>
        <div class="header">
                <img src="https://i.ibb.co/7t5BdK2t/2.png" alt="Team Eklavya Logo" class="logo" />
                <h1>${event.title}</h1>
                <p>Your Event Ticket</p>
            </div>
        </center>
        
        <!-- Main Content -->
        <div class="content">
            <div class="ticket-card">
                <h2 class="greeting">Hello ${user.firstName} ${user.lastName}!</h2>
                
                <p style="color: #6c757d; margin-bottom: 20px; font-size: 15px; line-height: 1.6;">
                    Your ticket for <strong style="color: #2c3e50;">${event.title}</strong> has been generated successfully! 
                    We're excited to have you join us for this amazing event.
                </p>
                
                <!-- Event Details -->
                <div class="event-details">
                    <h3>Event Details</h3>
                    <div class="detail-row">
                        <span class="detail-label">Event Name:</span>
                        <span class="detail-value"> ${event.title}</span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Date:</span>
                        <span class="detail-value"> ${new Date(event.startDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Time:</span>
                        <span class="detail-value"> ${event.startTime} - ${event.endTime}</span>
                    </div>
                    <div class="detail-row">
                        <span class="detail-label">Venue:</span>
                        <span class="detail-value"> ${event.venue}</span>
                    </div>
                </div>
                
                <!-- QR Code Section -->
                <div class="qr-section">
                    <h3 style="color: #2c3e50; margin-bottom: 15px; font-size: 16px; font-weight: 600;">🎫 Your Digital Ticket</h3>
                    <img src="${ticket.qrCode}" alt="QR Code for Event Ticket" class="qr-code" />
                    <p style="color: #6c757d; font-size: 13px; margin-top: 12px; line-height: 1.5;">
                        Present this QR code at the event entrance for scanning
                    </p>
                </div>
                
                <!-- Important Note -->
                <div class="important-note">
                    <p>📍 <strong>Important:</strong> Please keep this ticket safe and present the QR code at the event entrance. 
                    This ticket is non-transferable and valid for one person only.</p>
                </div>
                
                <p style="color: #6c757d; font-size: 14px; text-align: center; margin-top: 20px; line-height: 1.5;">
                    Can't wait to see you at the event! 🎊
                </p>
            </div>
        </div>
        
        <!-- Footer -->
        <div class="footer">
            <h3 style="margin-bottom: 15px; font-size: 18px; font-weight: 600;">Team Eklavya</h3>
            <p style="opacity: 0.9; margin-bottom: 20px; font-size: 14px;">Connecting students, creating opportunities</p>
            
            <!-- Social Media Links -->
            <div class="social-links">
                <a href="https://www.instagram.com/iteameklavya" class="social-link" target="_blank" style="color: #E4405F;">
                    <span class="social-icon">IG</span>
                </a>
                <a href="https://x.com/iteameklavya" class="social-link" target="_blank" style="color: #1DA1F2;">
                    <span class="social-icon">X</span>
                </a>
                <a href="https://www.linkedin.com/company/i-team-eklavya" class="social-link" target="_blank" style="color: #0A66C2;">
                    <span class="social-icon">IN</span>
                </a>
                <a href="https://chat.whatsapp.com/L7HvHNOatFbHIWM7EGBaaA" class="social-link" target="_blank" style="color: #25D366;">
                    <span class="social-icon">WA</span>
                </a>
            </div>
            
            <div class="contact-info">
                <p>Have questions? Reach out to us through our social media handles</p>
                <p style="margin-top: 12px; font-size: 12px; opacity: 0.7;">
                    &copy; ${new Date().getFullYear()} Team Eklavya. All rights reserved.
                </p>
            </div>
        </div>
    </div>
</body>
</html>
      `;

      await sendEmailWithAttachment({
        to: user.email,
        subject: `🎫 Your Ticket for ${event.title} - Team Eklavya`,
        html: htmlContent,
      });

      console.log(`✅ Ticket email sent to ${user.email}`);
      
      // Update ticket to mark email as sent
      await Ticket.findByIdAndUpdate(ticket._id, { emailSent: true, emailSentAt: new Date() });

    } catch (error) {
      console.error("❌ Failed to send ticket email:", error);
      throw error;
    }
  }

  // Generate tickets in bulk for multiple users
  async generateBulkTickets(eventId, userIds, options = {}) {
    try {
      const results = [];
      
      for (const userId of userIds) {
        try {
          const result = await this.generateTicket(eventId, userId, {
            ...options,
            autoGenerated: true,
          });
          results.push({
            userId,
            success: true,
            ticket: result.ticket,
            message: result.message,
          });
        } catch (error) {
          results.push({
            userId,
            success: false,
            error: error.message,
          });
        }
      }

      return {
        success: true,
        results,
        message: `Generated tickets for ${results.filter(r => r.success).length} users`,
      };
    } catch (error) {
      console.error("Bulk ticket generation error:", error);
      throw error;
    }
  }

  // Approve pending tickets (send emails)
  async approvePendingTickets(ticketIds) {
    try {
      const tickets = await Ticket.find({ 
        _id: { $in: ticketIds },
        status: 'pending' 
      }).populate('userId').populate('eventId');

      const results = [];
      
      for (const ticket of tickets) {
        try {
          await this.sendTicketEmail(ticket, ticket.userId, ticket.eventId);
          ticket.status = 'active';
          ticket.approvedAt = new Date();
          await ticket.save();
          
          results.push({
            ticketId: ticket._id,
            success: true,
            message: `Ticket approved and email sent to ${ticket.userId.email}`
          });
        } catch (error) {
          results.push({
            ticketId: ticket._id,
            success: false,
            error: error.message
          });
        }
      }

      return {
        success: true,
        results,
        message: `Approved ${results.filter(r => r.success).length} tickets`
      };
    } catch (error) {
      console.error("Approve pending tickets error:", error);
      throw error;
    }
  }

  // Get pending tickets for an event
  async getPendingTickets(eventId) {
    try {
      const tickets = await Ticket.find({ 
        eventId, 
        status: 'pending' 
      })
      .populate('userId', 'firstName lastName email profile')
      .sort({ createdAt: -1 });

      return tickets;
    } catch (error) {
      console.error("Get pending tickets error:", error);
      throw error;
    }
  }

  // Resend ticket email
  async resendTicketEmail(ticketId) {
    try {
      const ticket = await Ticket.findById(ticketId)
        .populate('userId')
        .populate('eventId');

      if (!ticket) {
        throw new Error("Ticket not found");
      }

      if (ticket.status !== 'active') {
        throw new Error("Cannot send email for inactive or pending ticket");
      }

      await this.sendTicketEmail(ticket, ticket.userId, ticket.eventId);

      return {
        success: true,
        message: `Ticket email resent to ${ticket.userId.email}`
      };
    } catch (error) {
      console.error("Resend ticket email error:", error);
      throw error;
    }
  }
}

module.exports = new TicketService();