const mongoose = require("mongoose");

/** A single message inside a conversation. */
const messageSchema = new mongoose.Schema(
  {
    conversation: { type: mongoose.Schema.Types.ObjectId, ref: "Conversation", required: true },
    sender: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
    content: { type: String, maxlength: 2000, trim: true, default: "" },

    /* ── Idempotency (Part 10 §11) ──────────────────────────────────────
     * Generated by the client when the user hits send, sent back on every
     * retry of that same send. Without it a retry after a timeout — or a
     * Socket.IO reconnect replaying a queued send — inserts a second copy
     * of a message the user believes was already sent.
     *
     * Sparse + unique: messages created before this field existed (and
     * messages from surfaces that legitimately have no client id) carry no
     * value and must not collide on `null`. */
    clientMessageId: {
      type: String,
      maxlength: 64,
      default: undefined,
      /* partialFilterExpression, not `sparse`. `sparse` excludes documents
       * where the field is *missing* but still indexes an explicit null, so
       * two clients that both send `clientMessageId: null` would collide on
       * the unique constraint. The partial filter indexes only real string
       * ids, which is exactly the set that must be unique. */
      index: { unique: true, partialFilterExpression: { clientMessageId: { $type: "string" } } },
    },
    // Optional image attachment (uploaded via /upload/image?folder=messages)
    image: { type: String, default: "" },
    // Soft-delete (unsend): content wiped for everyone, record kept for audit
    deletedAt: { type: Date, default: null },
    readAt: { type: Date, default: null },

    // ── Reactions (Part 8 §31) ──────────────────────────────────────────
    // Stored per-user-per-emoji rather than as a Set, so the UI can show
    // "❤️ 2 🔥 1" with counts and highlight the viewer's own pick.
    reactions: [
      {
        user: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
        emoji: { type: String, required: true, maxlength: 16 },
        at: { type: Date, default: Date.now },
      },
    ],

    // ── Reply target (Part 8 §30) ───────────────────────────────────────
    replyTo: { type: mongoose.Schema.Types.ObjectId, ref: "Message", default: null },

    /** Optional attachment metadata — files beyond the image field. */
    attachment: {
      url: { type: String, default: "" },
      name: { type: String, default: "" },
      size: { type: Number, default: 0 },
      mime: { type: String, default: "" },
    },
  },
  { timestamps: true }
);

/* ── Indexes (Part 10 §15) ──────────────────────────────────────────────
 * Added only where a real query needs them. Each entry names the query it
 * serves; anything without a caller was deliberately left out.
 *
 * 1. { conversation, createdAt }  — the thread read, forward and backward.
 *    Every page of history is `find({conversation}).sort({createdAt:-1})`,
 *    and the `before=<id>` cursor is resolved to a (createdAt,_id) pair that
 *    this index serves directly. Pre-existing; kept.
 *
 * 2. { conversation, readAt, sender } — unread counts.
 *    `countDocuments({conversation: {$in: myConvos}, readAt: null,
 *    sender: {$ne: me}})` runs for the badge and for the conversation list.
 *    Without this index that is a full scan of the collection filtered
 *    afterwards; with it MongoDB seeks each conversation's unread head and
 *    applies `sender` from the index itself (covered — no document fetch).
 *
 *    Why not `lastReadAt` on the Conversation instead? Part 8 added that Map
 *    but nothing writes to it. Adopting it now would mean two sources of
 *    truth for "read" that can disagree, and a backfill of every existing
 *    conversation. `readAt` per message already is the truth; this index
 *    makes counting it cheap.
 *
 * 3. NOT a text index, deliberately. Server-side message search (§25) uses a
 *    case-insensitive regex scoped to the caller's own conversations, because
 *    users search by PREFIX — typing "hel" and expecting "hello". MongoDB's
 *    $text tokenises whole words and would not match "hel" against "hello" at
 *    all. The regex is bounded to `conversation: {$in: myThreads}`, so index
 *    (1) turns it into one bounded seek per conversation rather than a
 *    collection scan; the cost scales with the user's own message volume, not
 *    with the size of the collection. A text index would additionally tax
 *    every message insert for a query we are not issuing.
 *
 * NOT added: { conversation, sender, createdAt }. The spec lists it, but no
 * query filters on all three — the unread path is covered by (2) and the
 * thread path by (1). Adding it would cost write throughput on the hottest
 * write in the app for zero reads, which §15 explicitly warns against. */
messageSchema.index({ conversation: 1, createdAt: -1 });
messageSchema.index({ conversation: 1, readAt: 1, sender: 1 });

module.exports = mongoose.model("Message", messageSchema);
