// models/ticket.model.js
const mongoose = require("mongoose");

const ticketSchema = new mongoose.Schema(
  {
    eventId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Event",
      required: true,
    },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    qrCode: {
      type: String, // Base64 QR
      required: true,
    },
    token: {
      type: String,
      required: true,
      unique: true,
    },
    // NEW: Ticket status and generation info
    status: {
      type: String,
      enum: ["pending", "active", "cancelled"],
      default: "active",
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    
    checkedIn: { type: Boolean, default: false },
    checkInTime: Date,
    checkOutTime: Date,
    scanMethod: {
      type: String,
      enum: ['qr', 'manual'],
      default: 'qr'
    },
    deviceType: String,
    entryLogs: [
      {
        action: { type: String, enum: ["entry", "exit"] },
        timestamp: { type: Date, default: Date.now },
        scannedBy: { type: mongoose.Schema.Types.ObjectId, ref: "User" },
        scanMethod: String,
        deviceType: String
      },
    ],
  },
  { timestamps: true }
);

// Index for better performance
ticketSchema.index({ eventId: 1, userId: 1 });
// NOTE (Part 5, Phase 3): `token` declares `unique: true` at the field level,
// which already creates this index. The duplicate was removed — tickets are
// written on every registration, so this was pure write overhead.
ticketSchema.index({ status: 1 });
ticketSchema.index({ autoGenerated: 1 });

module.exports = mongoose.model("Ticket", ticketSchema);