"use client";

import { useEffect, useState, useMemo } from "react";
import { useParams, useRouter } from "next/navigation";
import { jwtDecode } from "jwt-decode";
import { api } from "@/utils/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  ArrowLeft, 
  Users, 
  CheckCircle, 
  Clock, 
  TrendingUp,
  Download,
  Calendar,
  MapPin,
  Ticket,
  UserCheck,
  UserX,
  Activity,
  Filter,
  RefreshCw,
  Eye,
  EyeOff,
  Mail,
  Target,
  AlertCircle,
  Search,
  FileText,
  User,
  CalendarDays,
  Building,
  BookOpen,
  GraduationCap,
  BarChart3,
  LogIn,
  LogOut,
  Send,
  Play,
  Pause,
  Settings,
  QrCode,
  MailCheck,
  MailWarning,
  Sparkles,
  Zap,
  Shield,
  Bell,
  MessageCircle,
  Link,
  ShieldCheck,
  RotateCcw
} from "lucide-react";
import { toast } from "sonner";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";

interface DecodedToken {
  id: string;
  role: string;
  exp: number;
}

interface Event {
  _id: string;
  title: string;
  startDate: string;
  endDate: string;
  venue: string;
  maxAttendees?: number;
  category?: string;
  price?: number;
  ticketSettings?: {
    autoGenerate: boolean;
    sendEmail: boolean;
    manualApproval: boolean;
  };
}

interface ScanStats {
  totalTickets: number;
  checkedInTickets: number;
  checkedOutTickets: number;
  attendanceRate: number;
  hourlyData: Array<{
    _id: { hour: number; date: string };
    count: number;
  }>;
  peakHours?: Array<{
    hour: number;
    count: number;
    percentage: number;
  }>;
  dailyData?: Array<{
    date: string;
    checkIns: number;
    checkOuts: number;
  }>;
}

interface RegistrationStats {
  totalRegistrations: number;
  confirmedRegistrations: number;
  pendingRegistrations: number;
  registrationRate: number;
  dailyRegistrations?: Array<{
    date: string;
    count: number;
  }>;
  sourceBreakdown?: {
    web: number;
    mobile: number;
    other: number;
  };
}

interface RecentScan {
  _id: string;
  userId?: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
    profile?: {
      institution?: string;
      course?: string;
    };
  };
  checkedIn: boolean;
  checkInTime?: string;
  checkOutTime?: string;
  scanMethod?: 'qr' | 'manual';
  deviceType?: string;
}

interface RegistrationResponse {
  _id: string;
  userId: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
    profile?: {
      institution?: string;
      course?: string;
      year?: string;
    };
  };
  answers: Array<{
    fieldLabel: string;
    fieldType: string;
    value: any;
  }>;
  createdAt: string;
  status: 'confirmed' | 'pending';
  rsvpSent?: boolean;
  rsvpSentAt?: string;
  rsvpToken?: string;
  rsvpVerified?: boolean;
  rsvpVerifiedAt?: string;
  rsvpVerificationExpires?: string;
  source?: 'web' | 'mobile' | 'admin';
  metadata?: {
    ipAddress?: string;
    userAgent?: string;
    referrer?: string;
  };
}

interface TicketData {
  _id: string;
  userId?: {
    _id: string;
    firstName: string;
    lastName: string;
    email: string;
  };
  status: 'active' | 'pending' | 'used' | 'cancelled';
  autoGenerated: boolean;
  emailSent: boolean;
  sentAt?: string;
  createdAt: string;
  checkedIn?: boolean;
  checkInTime?: string;
  checkOutTime?: string;
  scanMethod?: 'qr' | 'manual';
  deviceType?: string;
}

interface AnalyticsTimeRange {
  label: string;
  value: string;
  days: number;
}

interface RSVPAnalytics {
  totalRegistrations: number;
  rsvp: {
    sent: number;
    verified: number;
    expired: number;
    pending: number;
    sentRate: number;
    verificationRate: number;
    responseRate: number;
  };
  timeline: {
    last7Days: Array<{ _id: string; count: number }>;
    last30Days: Array<{ _id: string; count: number }>;
  };
}

// Fallback data generator
const generateFallbackScanStats = (event: Event | null): ScanStats => ({
  totalTickets: 0,
  checkedInTickets: 0,
  checkedOutTickets: 0,
  attendanceRate: 0,
  hourlyData: [],
  peakHours: [],
  dailyData: []
});

const generateFallbackRegistrationStats = (): RegistrationStats => ({
  totalRegistrations: 0,
  confirmedRegistrations: 0,
  pendingRegistrations: 0,
  registrationRate: 0,
  dailyRegistrations: [],
  sourceBreakdown: { web: 0, mobile: 0, other: 0 }
});

const generateFallbackRSVPAnalytics = (): RSVPAnalytics => ({
  totalRegistrations: 0,
  rsvp: {
    sent: 0,
    verified: 0,
    expired: 0,
    pending: 0,
    sentRate: 0,
    verificationRate: 0,
    responseRate: 0
  },
  timeline: {
    last7Days: [],
    last30Days: []
  }
});

export default function EventAnalyticsPage() {
  const router = useRouter();
  const { id } = useParams();
  const [event, setEvent] = useState<Event | null>(null);
  const [scanStats, setScanStats] = useState<ScanStats | null>(null);
  const [registrationStats, setRegistrationStats] = useState<RegistrationStats | null>(null);
  const [rsvpAnalytics, setRsvpAnalytics] = useState<RSVPAnalytics | null>(null);
  const [recentScans, setRecentScans] = useState<RecentScan[]>([]);
  const [registrations, setRegistrations] = useState<RegistrationResponse[]>([]);
  const [tickets, setTickets] = useState<TicketData[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [timeRange, setTimeRange] = useState<AnalyticsTimeRange>({
    label: "All Time",
    value: "all",
    days: 365
  });
  const [showDetailedView, setShowDetailedView] = useState(false);
  const [apiErrors, setApiErrors] = useState<string[]>([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [registrationFilter, setRegistrationFilter] = useState<'all' | 'confirmed' | 'pending'>('all');
  const [ticketSettings, setTicketSettings] = useState({
    autoGenerate: false,
    sendEmail: true,
    manualApproval: false
  });
  const [ticketActionsLoading, setTicketActionsLoading] = useState({
    generate: false,
    send: false,
    approve: false
  });
  const [notificationLoading, setNotificationLoading] = useState(false);
  const [rsvpLoading, setRsvpLoading] = useState(false);
  const [rsvpVerificationLoading, setRsvpVerificationLoading] = useState(false);
  const [selectedUsersForRSVP, setSelectedUsersForRSVP] = useState<string[]>([]);

  const timeRanges: AnalyticsTimeRange[] = [
    { label: "24H", value: "1d", days: 1 },
    { label: "7D", value: "7d", days: 7 },
    { label: "30D", value: "30d", days: 30 },
    { label: "All Time", value: "all", days: 365 }
  ];

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) {
      router.replace("/login");
      return;
    }

    try {
      const decoded: DecodedToken = jwtDecode(token);
      if (decoded.exp * 1000 < Date.now() || decoded.role !== "admin") {
        localStorage.clear();
        router.replace("/login");
        return;
      }
      fetchAnalyticsData();
    } catch (err) {
      console.error("Token decoding failed:", err);
      localStorage.clear();
      router.replace("/login");
    }
  }, [router, id, timeRange]);

  const fetchAnalyticsData = async () => {
    try {
      setLoading(true);
      setApiErrors([]);
      const token = localStorage.getItem("token");
      
      // Fetch event data
      const eventRes = await api.get(`/events/${id}`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      const eventData = eventRes.data.event;
      setEvent(eventData);
      
      // Set ticket settings from event
      if (eventData.ticketSettings) {
        setTicketSettings(eventData.ticketSettings);
      }

      // Try to fetch scan stats with fallback
      let scanStatsData: ScanStats | null = null;
      try {
        const statsRes = await api.get(`/tickets/event/${id}/stats`, {
          headers: { Authorization: `Bearer ${token}` },
          params: { timeRange: timeRange.value }
        });
        scanStatsData = statsRes.data.stats;
      } catch (error: any) {
        console.warn("Scan stats endpoint not available, using fallback data");
        scanStatsData = generateFallbackScanStats(eventData);
        setApiErrors(prev => [...prev, "Scan analytics temporarily unavailable"]);
      }
      setScanStats(scanStatsData);

      // Try to fetch registration stats with fallback
      let registrationStatsData: RegistrationStats | null = null;
      try {
        const registrationsRes = await api.get(`/registration/responses/${id}/stats`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        registrationStatsData = registrationsRes.data.stats;
      } catch (error: any) {
        console.warn("Registration stats endpoint not available, using fallback data");
        registrationStatsData = generateFallbackRegistrationStats();
        setApiErrors(prev => [...prev, "Registration analytics temporarily unavailable"]);
      }
      setRegistrationStats(registrationStatsData);

      // Try to fetch RSVP analytics
      let rsvpAnalyticsData: RSVPAnalytics | null = null;
      try {
        const rsvpRes = await api.get(`/events/${id}/rsvp-analytics`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        rsvpAnalyticsData = rsvpRes.data.analytics;
      } catch (error: any) {
        console.warn("RSVP analytics endpoint not available, using fallback data");
        rsvpAnalyticsData = generateFallbackRSVPAnalytics();
        setApiErrors(prev => [...prev, "RSVP analytics temporarily unavailable"]);
      }
      setRsvpAnalytics(rsvpAnalyticsData);

      // Try to fetch recent scans with fallback
      let recentScansData: RecentScan[] = [];
      try {
        const scansRes = await api.get(`/tickets/event/${id}/recent-scans`, {
          headers: { Authorization: `Bearer ${token}` },
          params: { limit: 1000 }
        });
        recentScansData = scansRes.data.scans || [];
      } catch (error: any) {
        console.warn("Recent scans endpoint not available, using empty array");
        setApiErrors(prev => [...prev, "Recent scans temporarily unavailable"]);
      }
      setRecentScans(recentScansData);

      // Fetch registration responses
      try {
        const registrationsRes = await api.get(`/registration/responses/${id}`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (registrationsRes.data.success) {
          setRegistrations(registrationsRes.data.responses || []);
        }
      } catch (error: any) {
        console.warn("Registration responses endpoint not available");
        setApiErrors(prev => [...prev, "Registration list temporarily unavailable"]);
      }

      // Fetch tickets data
      try {
        const ticketsRes = await api.get(`/tickets/event/${id}/scanned-tickets`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        if (ticketsRes.data.success) {
          setTickets(ticketsRes.data.tickets || []);
        }
      } catch (error: any) {
        console.warn("Tickets endpoint not available");
        setApiErrors(prev => [...prev, "Ticket data temporarily unavailable"]);
      }

    } catch (err: any) {
      console.error("Failed to fetch analytics data", err);
      const errorMessage = err.response?.data?.message || "Failed to load analytics";
      toast.error(errorMessage);
      
      // Set fallback data if main fetch fails
      setScanStats(generateFallbackScanStats(null));
      setRegistrationStats(generateFallbackRegistrationStats());
      setRsvpAnalytics(generateFallbackRSVPAnalytics());
      setRecentScans([]);
      setRegistrations([]);
      setTickets([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  const handleRefresh = () => {
    setRefreshing(true);
    setApiErrors([]);
    fetchAnalyticsData();
  };

  // Get scan data for a specific registration
  const getRegistrationScanData = (registration: RegistrationResponse) => {
    return recentScans.find(scan => 
      scan.userId && scan.userId.email === registration.userId.email
    );
  };

  // Get ticket data for a specific registration
  const getRegistrationTicketData = (registration: RegistrationResponse) => {
    return tickets.find(ticket => 
      ticket.userId && ticket.userId.email === registration.userId.email
    );
  };

  // Get RSVP verification status
  const getRSVPVerificationStatus = (registration: RegistrationResponse) => {
    if (!registration.rsvpToken) return 'not-sent';
    if (registration.rsvpVerified) return 'verified';
    if (registration.rsvpVerificationExpires && new Date(registration.rsvpVerificationExpires) < new Date()) {
      return 'expired';
    }
    return 'pending';
  };

  // Ticket Management Functions
  const generateTicketsForRegistrations = async () => {
    try {
      setTicketActionsLoading(prev => ({ ...prev, generate: true }));
      const token = localStorage.getItem("token");
      
      const registrationsWithoutTickets = registrations.filter(reg => 
        !tickets.some(ticket => ticket.userId?._id === reg.userId._id)
      );

      if (registrationsWithoutTickets.length === 0) {
        toast.info("All registrations already have tickets");
        return;
      }

      const response = await api.post(`/tickets/bulk-generate`, {
        eventId: id,
        userIds: registrationsWithoutTickets.map(reg => reg.userId._id)
      }, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        toast.success(`Generated ${response.data.generated} tickets successfully`);
        fetchAnalyticsData(); // Refresh data
      } else {
        throw new Error(response.data.message || "Failed to generate tickets");
      }
    } catch (error: any) {
      console.error("Generate tickets error:", error);
      toast.error(error.response?.data?.message || "Failed to generate tickets");
    } finally {
      setTicketActionsLoading(prev => ({ ...prev, generate: false }));
    }
  };

  const sendTicketsToUsers = async () => {
    try {
      setTicketActionsLoading(prev => ({ ...prev, send: true }));
      const token = localStorage.getItem("token");
      
      const ticketsToSend = tickets.filter(ticket => 
        ticket.status === 'active' && !ticket.emailSent
      );

      if (ticketsToSend.length === 0) {
        toast.info("All active tickets have already been sent");
        return;
      }

      let sentCount = 0;
      let errorCount = 0;

      // Send tickets one by one with progress
      for (const ticket of ticketsToSend) {
        try {
          await api.post(`/tickets/send-ticket`, {
            ticketId: ticket._id,
            userId: ticket.userId?._id
          }, {
            headers: { Authorization: `Bearer ${token}` },
          });
          sentCount++;
          
          // Update progress every 10 tickets
          if (sentCount % 10 === 0) {
            toast.info(`Sent ${sentCount} of ${ticketsToSend.length} tickets...`);
          }
        } catch (error) {
          console.error(`Failed to send ticket to ${ticket.userId?.email}:`, error);
          errorCount++;
        }
      }

      if (sentCount > 0) {
        toast.success(`Successfully sent ${sentCount} tickets${errorCount > 0 ? `, ${errorCount} failed` : ''}`);
      }
      if (errorCount > 0) {
        toast.error(`${errorCount} tickets failed to send`);
      }

      fetchAnalyticsData(); // Refresh data
    } catch (error: any) {
      console.error("Send tickets error:", error);
      toast.error(error.response?.data?.message || "Failed to send tickets");
    } finally {
      setTicketActionsLoading(prev => ({ ...prev, send: false }));
    }
  };

  const approvePendingTickets = async () => {
    try {
      setTicketActionsLoading(prev => ({ ...prev, approve: true }));
      const token = localStorage.getItem("token");
      
      const response = await api.post(`/tickets/approve-pending`, {
        eventId: id
      }, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        toast.success(`Approved ${response.data.approved} pending tickets`);
        fetchAnalyticsData(); // Refresh data
      } else {
        throw new Error(response.data.message || "Failed to approve tickets");
      }
    } catch (error: any) {
      console.error("Approve tickets error:", error);
      toast.error(error.response?.data?.message || "Failed to approve tickets");
    } finally {
      setTicketActionsLoading(prev => ({ ...prev, approve: false }));
    }
  };

  const updateTicketSettings = async (newSettings: any) => {
    try {
      const token = localStorage.getItem("token");
      const response = await api.patch(`/events/${id}/ticket-settings`, {
        ticketSettings: newSettings
      }, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        setTicketSettings(newSettings);
        toast.success("Ticket settings updated successfully");
        fetchAnalyticsData(); // Refresh to get updated event data
      } else {
        throw new Error(response.data.message || "Failed to update settings");
      }
    } catch (error: any) {
      console.error("Update ticket settings error:", error);
      toast.error(error.response?.data?.message || "Failed to update ticket settings");
    }
  };

  const handleTicketSettingChange = (setting: keyof typeof ticketSettings, value: boolean) => {
    const newSettings = { ...ticketSettings, [setting]: value };
    updateTicketSettings(newSettings);
  };

  // Send notification to all users about new event
  const sendEventNotification = async () => {
    try {
      setNotificationLoading(true);
      const token = localStorage.getItem("token");
      
      const response = await api.post(`/events/${id}/notify-all`, {}, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        toast.success(`Notification sent to ${response.data.sentCount} users`);
      } else {
        throw new Error(response.data.message || "Failed to send notification");
      }
    } catch (error: any) {
      console.error("Send notification error:", error);
      toast.error(error.response?.data?.message || "Failed to send notification");
    } finally {
      setNotificationLoading(false);
    }
  };

  // Send RSVP emails to registered students with tickets
  const sendRSVPToRegisteredStudents = async () => {
    try {
      setRsvpLoading(true);
      const token = localStorage.getItem("token");
      
      const studentsWithTickets = registrations.filter(reg => {
        const hasTicket = tickets.some(ticket => 
          ticket.userId?._id === reg.userId._id && ticket.status === 'active'
        );
        return hasTicket && reg.status === 'confirmed';
      });

      if (studentsWithTickets.length === 0) {
        toast.info("No registered students with active tickets found");
        return;
      }

      const response = await api.post(`/events/rsvp-registered/${id}`, {
        userIds: studentsWithTickets.map(reg => reg.userId._id)
      }, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        toast.success(`RSVP sent to ${response.data.sentCount} students`);
        fetchAnalyticsData(); // Refresh to get updated RSVP status
      } else {
        throw new Error(response.data.message || "Failed to send RSVP");
      }
    } catch (error: any) {
      console.error("Send RSVP error:", error);
      toast.error(error.response?.data?.message || "Failed to send RSVP");
    } finally {
      setRsvpLoading(false);
    }
  };

  // Send RSVP with verification links
  const sendRSVPWithVerification = async () => {
    try {
      setRsvpVerificationLoading(true);
      const token = localStorage.getItem("token");
      
      const userIds = selectedUsersForRSVP.length > 0 
        ? selectedUsersForRSVP 
        : registrations.map(reg => reg.userId._id);

      if (userIds.length === 0) {
        toast.info("No users selected to send RSVP");
        return;
      }

      const response = await api.post(`/events/rsvp/send-with-verification`, {
        eventId: id,
        userIds: userIds,
        customMessage: `You're invited to ${event?.title}! Please confirm your attendance.`
      }, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        toast.success(`RSVP with verification links sent to ${response.data.results.filter((r: any) => r.status === 'sent').length} users`);
        setSelectedUsersForRSVP([]);
        fetchAnalyticsData(); // Refresh data
      } else {
        throw new Error(response.data.message || "Failed to send RSVP with verification");
      }
    } catch (error: any) {
      console.error("Send RSVP with verification error:", error);
      toast.error(error.response?.data?.message || "Failed to send RSVP with verification");
    } finally {
      setRsvpVerificationLoading(false);
    }
  };

  // Resend verification link to specific users
  const resendVerificationLink = async (registrationId: string) => {
    try {
      const token = localStorage.getItem("token");
      const response = await api.post(`/events/rsvp/resend-verification`, {
        registrationId
      }, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (response.data.success) {
        toast.success("Verification link resent successfully");
        fetchAnalyticsData(); // Refresh data
      } else {
        throw new Error(response.data.message || "Failed to resend verification link");
      }
    } catch (error: any) {
      console.error("Resend verification link error:", error);
      toast.error(error.response?.data?.message || "Failed to resend verification link");
    }
  };

  const exportAnalyticsData = async (type: 'scans' | 'registrations' | 'all' | 'registration-list' | 'tickets' | 'rsvp') => {
    try {
      const token = localStorage.getItem("token");
      
      let csvContent = "";
      let filename = "";

      switch (type) {
        case 'scans':
          filename = `scan-data-${event?.title}-${new Date().toISOString().split('T')[0]}.csv`;
          csvContent = "Name,Email,Check-in Time,Check-out Time,Status,Scan Method,Device Type\n";
          recentScans.forEach(scan => {
            const name = scan.userId ? `${scan.userId.firstName} ${scan.userId.lastName}` : 'Unknown User';
            const email = scan.userId?.email || 'No email';
            const checkInTime = scan.checkInTime ? new Date(scan.checkInTime).toLocaleString() : 'N/A';
            const checkOutTime = scan.checkOutTime ? new Date(scan.checkOutTime).toLocaleString() : 'N/A';
            const status = scan.checkedIn ? (scan.checkOutTime ? 'Checked Out' : 'Checked In') : 'Pending';
            const scanMethod = scan.scanMethod || 'qr';
            const deviceType = scan.deviceType || 'Unknown';
            csvContent += `"${name}","${email}","${checkInTime}","${checkOutTime}","${status}","${scanMethod}","${deviceType}"\n`;
          });
          break;
        
        case 'registrations':
          filename = `registration-stats-${event?.title}-${new Date().toISOString().split('T')[0]}.csv`;
          csvContent = "Event,Total Registrations,Confirmed,Pending,Registration Rate\n";
          if (registrationStats) {
            csvContent += `"${event?.title}",${registrationStats.totalRegistrations},${registrationStats.confirmedRegistrations},${registrationStats.pendingRegistrations},${registrationStats.registrationRate}%\n`;
          }
          break;

        case 'rsvp':
          filename = `rsvp-analytics-${event?.title}-${new Date().toISOString().split('T')[0]}.csv`;
          csvContent = "Metric,Value\n";
          if (rsvpAnalytics) {
            csvContent += `Total Registrations,${rsvpAnalytics.totalRegistrations}\n`;
            csvContent += `RSVP Sent,${rsvpAnalytics.rsvp.sent}\n`;
            csvContent += `RSVP Verified,${rsvpAnalytics.rsvp.verified}\n`;
            csvContent += `RSVP Pending,${rsvpAnalytics.rsvp.pending}\n`;
            csvContent += `RSVP Expired,${rsvpAnalytics.rsvp.expired}\n`;
            csvContent += `Verification Rate,${rsvpAnalytics.rsvp.verificationRate}%\n`;
            csvContent += `Response Rate,${rsvpAnalytics.rsvp.responseRate}%\n`;
          }
          break;

        case 'registration-list':
          filename = `registration-list-${event?.title}-${new Date().toISOString().split('T')[0]}.csv`;
          const headers = ['Name', 'Email', 'Registration Date', 'Status', 'Ticket Status', 'RSVP Status', 'RSVP Sent', 'RSVP Verified', 'Verification Date', 'Check-in Time', 'Check-out Time', 'Scan Method', 'Source', 'Institution', 'Course', 'Year'];
          if (registrations.length > 0 && registrations[0].answers) {
            registrations[0].answers.forEach(answer => {
              headers.push(answer.fieldLabel);
            });
          }
          csvContent = headers.join(',') + '\n';
          
          filteredRegistrations.forEach(reg => {
            const userScan = recentScans.find(scan => 
              scan.userId && scan.userId.email === reg.userId.email
            );
            
            const userTicket = tickets.find(ticket => 
              ticket.userId && ticket.userId.email === reg.userId.email
            );

            const ticketStatus = userTicket ? 
              userTicket.status.charAt(0).toUpperCase() + userTicket.status.slice(1) : 
              'Not Generated';

            const rsvpStatus = getRSVPVerificationStatus(reg);
            const rsvpStatusText = 
              rsvpStatus === 'verified' ? 'Verified' :
              rsvpStatus === 'pending' ? 'Pending Verification' :
              rsvpStatus === 'expired' ? 'Expired' : 'Not Sent';

            const checkInTime = userScan?.checkInTime ? 
              new Date(userScan.checkInTime).toLocaleString() : 'N/A';
            const checkOutTime = userScan?.checkOutTime ? 
              new Date(userScan.checkOutTime).toLocaleString() : 'N/A';

            const row = [
              `"${reg.userId.firstName} ${reg.userId.lastName}"`,
              `"${reg.userId.email}"`,
              `"${new Date(reg.createdAt).toLocaleDateString()}"`,
              `"${reg.status}"`,
              `"${ticketStatus}"`,
              `"${rsvpStatusText}"`,
              `"${reg.rsvpSent ? 'Yes' : 'No'}"`,
              `"${reg.rsvpVerified ? 'Yes' : 'No'}"`,
              `"${reg.rsvpVerifiedAt ? new Date(reg.rsvpVerifiedAt).toLocaleString() : 'N/A'}"`,
              `"${checkInTime}"`,
              `"${checkOutTime}"`,
              `"${userScan?.scanMethod || 'N/A'}"`,
              `"${reg.source || 'web'}"`,
              `"${reg.userId.profile?.institution || 'N/A'}"`,
              `"${reg.userId.profile?.course || 'N/A'}"`,
              `"${reg.userId.profile?.year || 'N/A'}"`
            ];
            
            reg.answers.forEach(answer => {
              let value = answer.value;
              if (typeof value === 'object') value = JSON.stringify(value);
              if (typeof value === 'boolean') value = value ? 'Yes' : 'No';
              row.push(`"${value}"`);
            });
            
            csvContent += row.join(',') + '\n';
          });
          break;

        case 'tickets':
          filename = `ticket-data-${event?.title}-${new Date().toISOString().split('T')[0]}.csv`;
          csvContent = "Name,Email,Ticket Status,Email Sent,Sent At,Auto Generated,Created At,Checked In,Check-in Time,Check-out Time,Scan Method\n";
          tickets.forEach(ticket => {
            const name = ticket.userId ? `${ticket.userId.firstName} ${ticket.userId.lastName}` : 'Unknown User';
            const email = ticket.userId?.email || 'No email';
            const status = ticket.status;
            const emailSent = ticket.emailSent ? 'Yes' : 'No';
            const sentAt = ticket.sentAt ? new Date(ticket.sentAt).toLocaleString() : 'N/A';
            const autoGenerated = ticket.autoGenerated ? 'Yes' : 'No';
            const createdAt = new Date(ticket.createdAt).toLocaleString();
            const checkedIn = ticket.checkedIn ? 'Yes' : 'No';
            const checkInTime = ticket.checkInTime ? new Date(ticket.checkInTime).toLocaleString() : 'N/A';
            const checkOutTime = ticket.checkOutTime ? new Date(ticket.checkOutTime).toLocaleString() : 'N/A';
            const scanMethod = ticket.scanMethod || 'N/A';
            
            csvContent += `"${name}","${email}","${status}","${emailSent}","${sentAt}","${autoGenerated}","${createdAt}","${checkedIn}","${checkInTime}","${checkOutTime}","${scanMethod}"\n`;
          });
          break;
        
        case 'all':
          filename = `full-analytics-${event?.title}-${new Date().toISOString().split('T')[0]}.csv`;
          csvContent = "Metric,Value\n";
          if (scanStats) {
            csvContent += `Total Tickets,${scanStats.totalTickets}\n`;
            csvContent += `Checked In,${scanStats.checkedInTickets}\n`;
            csvContent += `Checked Out,${scanStats.checkedOutTickets}\n`;
            csvContent += `Attendance Rate,${scanStats.attendanceRate}%\n`;
          }
          if (registrationStats) {
            csvContent += `Total Registrations,${registrationStats.totalRegistrations}\n`;
            csvContent += `Confirmed Registrations,${registrationStats.confirmedRegistrations}\n`;
            csvContent += `Pending Registrations,${registrationStats.pendingRegistrations}\n`;
            csvContent += `Registration Rate,${registrationStats.registrationRate}%\n`;
          }
          if (rsvpAnalytics) {
            csvContent += `RSVP Sent,${rsvpAnalytics.rsvp.sent}\n`;
            csvContent += `RSVP Verified,${rsvpAnalytics.rsvp.verified}\n`;
            csvContent += `RSVP Verification Rate,${rsvpAnalytics.rsvp.verificationRate}%\n`;
          }
          if (tickets.length > 0) {
            const activeTickets = tickets.filter(t => t.status === 'active').length;
            const pendingTickets = tickets.filter(t => t.status === 'pending').length;
            const sentTickets = tickets.filter(t => t.emailSent).length;
            csvContent += `Active Tickets,${activeTickets}\n`;
            csvContent += `Pending Tickets,${pendingTickets}\n`;
            csvContent += `Sent Tickets,${sentTickets}\n`;
          }
          break;
      }

      const blob = new Blob([csvContent], { type: 'text/csv' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);
      
      toast.success(`${
        type === 'scans' ? 'Scan data' : 
        type === 'registrations' ? 'Registration stats' : 
        type === 'rsvp' ? 'RSVP analytics' :
        type === 'registration-list' ? 'Registration list' :
        type === 'tickets' ? 'Ticket data' :
        'Full analytics'
      } exported successfully!`);
    } catch (error: any) {
      console.error("Export error:", error);
      toast.error("Failed to export data. Please try again.");
    }
  };

  // Filter registrations based on search and filter
  const filteredRegistrations = useMemo(() => {
    return registrations.filter(reg => {
      const matchesSearch = 
        reg.userId.firstName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        reg.userId.lastName.toLowerCase().includes(searchTerm.toLowerCase()) ||
        reg.userId.email.toLowerCase().includes(searchTerm.toLowerCase()) ||
        reg.userId.profile?.institution?.toLowerCase().includes(searchTerm.toLowerCase()) ||
        reg.userId.profile?.course?.toLowerCase().includes(searchTerm.toLowerCase());
      
      const matchesFilter = 
        registrationFilter === 'all' || 
        reg.status === registrationFilter;
      
      return matchesSearch && matchesFilter;
    });
  }, [registrations, searchTerm, registrationFilter]);

  // Memoized calculations for better performance
  const calculatedMetrics = useMemo(() => {
    if (!scanStats || !registrationStats) return null;

    const currentTime = new Date();
    const eventStart = event ? new Date(event.startDate) : currentTime;
    const eventEnd = event ? new Date(event.endDate) : currentTime;
    
    const isEventActive = currentTime >= eventStart && currentTime <= eventEnd;
    const isEventFuture = currentTime < eventStart;
    const isEventPast = currentTime > eventEnd;

    const totalCapacity = event?.maxAttendees || 100;
    const registrationFillRate = (registrationStats?.totalRegistrations / totalCapacity) * 100;
    const attendanceFillRate = (scanStats?.checkedInTickets / totalCapacity) * 100;

    // Ticket metrics
    const totalTickets = tickets.length;
    const activeTickets = tickets.filter(t => t.status === 'active').length;
    const pendingTickets = tickets.filter(t => t.status === 'pending').length;
    const sentTickets = tickets.filter(t => t.emailSent).length;
    const sentTicketRate = totalTickets > 0 ? (sentTickets / totalTickets) * 100 : 0;
    const registrationsWithoutTickets = registrationStats.totalRegistrations - totalTickets;

    // RSVP metrics
    const rsvpSentCount = registrations.filter(reg => reg.rsvpSent).length;
    const rsvpVerifiedCount = registrations.filter(reg => reg.rsvpVerified).length;
    const rsvpRate = registrations.length > 0 ? (rsvpSentCount / registrations.length) * 100 : 0;
    const rsvpVerificationRate = rsvpSentCount > 0 ? (rsvpVerifiedCount / rsvpSentCount) * 100 : 0;

    return {
      isEventActive,
      isEventFuture,
      isEventPast,
      registrationFillRate: Math.min(registrationFillRate, 100),
      attendanceFillRate: Math.min(attendanceFillRate, 100),
      remainingCapacity: Math.max(0, totalCapacity - scanStats.checkedInTickets),
      // Ticket metrics
      totalTickets,
      activeTickets,
      pendingTickets,
      sentTickets,
      sentTicketRate,
      registrationsWithoutTickets,
      // RSVP metrics
      rsvpSentCount,
      rsvpVerifiedCount,
      rsvpRate,
      rsvpVerificationRate
    };
  }, [scanStats, registrationStats, event, tickets, registrations]);

  // Ticket statistics
  const ticketStats = useMemo(() => {
    const totalTickets = tickets.length;
    const activeTickets = tickets.filter(t => t.status === 'active').length;
    const pendingTickets = tickets.filter(t => t.status === 'pending').length;
    const usedTickets = tickets.filter(t => t.checkedIn).length;
    const sentTickets = tickets.filter(t => t.emailSent).length;
    const autoGeneratedTickets = tickets.filter(t => t.autoGenerated).length;

    return {
      totalTickets,
      activeTickets,
      pendingTickets,
      usedTickets,
      sentTickets,
      autoGeneratedTickets,
      sentTicketRate: totalTickets > 0 ? (sentTickets / totalTickets) * 100 : 0,
      usageRate: totalTickets > 0 ? (usedTickets / totalTickets) * 100 : 0
    };
  }, [tickets]);

  // RSVP statistics
  const rsvpStats = useMemo(() => {
    const totalRegistrations = registrations.length;
    const rsvpSent = registrations.filter(reg => reg.rsvpSent).length;
    const rsvpVerified = registrations.filter(reg => reg.rsvpVerified).length;
    const rsvpPending = registrations.filter(reg => 
      reg.rsvpSent && !reg.rsvpVerified && 
      (!reg.rsvpVerificationExpires || new Date(reg.rsvpVerificationExpires) > new Date())
    ).length;
    const rsvpExpired = registrations.filter(reg => 
      reg.rsvpSent && !reg.rsvpVerified && 
      reg.rsvpVerificationExpires && new Date(reg.rsvpVerificationExpires) < new Date()
    ).length;

    return {
      totalRegistrations,
      rsvpSent,
      rsvpVerified,
      rsvpPending,
      rsvpExpired,
      sentRate: totalRegistrations > 0 ? (rsvpSent / totalRegistrations) * 100 : 0,
      verificationRate: rsvpSent > 0 ? (rsvpVerified / rsvpSent) * 100 : 0
    };
  }, [registrations]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 p-4 sm:p-6">
        <div className="max-w-7xl mx-auto">
          <div className="animate-pulse space-y-6">
            {/* Header Skeleton */}
            <div className="h-8 bg-gray-200 rounded w-48 sm:w-64 mb-2"></div>
            <div className="h-4 bg-gray-200 rounded w-72 sm:w-96 mb-8"></div>
            
            {/* Stats Grid Skeleton */}
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6 mb-8">
              {[1, 2, 3, 4].map(i => (
                <div key={i} className="bg-white rounded-xl shadow-sm p-4 sm:p-6 h-28 sm:h-32">
                  <div className="flex justify-between items-start">
                    <div className="space-y-2 sm:space-y-3">
                      <div className="h-4 bg-gray-200 rounded w-16 sm:w-24"></div>
                      <div className="h-6 sm:h-8 bg-gray-200 rounded w-12 sm:w-16"></div>
                    </div>
                    <div className="h-8 w-8 sm:h-10 sm:w-10 bg-gray-200 rounded-xl"></div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50">
      {/* Enhanced Header with Gradient */}
      <div className="bg-gradient-to-r from-blue-600 via-purple-600 to-indigo-700 text-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex flex-col space-y-4 sm:space-y-6">
            {/* Top Navigation */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-4 sm:space-y-0">
              <div className="flex flex-col sm:flex-row sm:items-center space-y-3 sm:space-y-0 sm:space-x-4">
                <Button
                  variant="ghost"
                  onClick={() => router.push(`/admin/events`)}
                  className="bg-white/10 hover:bg-white/20 text-white border-white/20 w-fit"
                >
                  <ArrowLeft className="h-4 w-4 mr-2" />
                  Back to Events
                </Button>
                <div className="space-y-1">
                  <h1 className="text-2xl sm:text-3xl font-bold text-white">
                    Event Analytics
                  </h1>
                  <p className="text-blue-100 text-sm">{event?.title}</p>
                </div>
              </div>
              
              <div className="flex flex-wrap gap-2 sm:gap-3">
                <Button
                  onClick={handleRefresh}
                  disabled={refreshing}
                  className="bg-white/10 hover:bg-white/20 text-white border-white/20"
                >
                  <RefreshCw className={`h-4 w-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
                  {refreshing ? "Refreshing..." : "Refresh"}
                </Button>
                
                <Button
                  onClick={() => exportAnalyticsData('all')}
                  className="bg-white text-blue-600 hover:bg-blue-50 shadow-sm"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Export All
                </Button>
              </div>
            </div>

            {/* API Error Warnings */}
            {apiErrors.length > 0 && (
              <div className="bg-amber-500/20 border border-amber-400/30 rounded-lg p-3 sm:p-4 backdrop-blur-sm">
                <div className="flex items-center space-x-2">
                  <AlertCircle className="h-4 w-4 sm:h-5 sm:w-5 text-amber-300" />
                  <span className="text-amber-100 font-medium text-sm sm:text-base">Some data may be limited</span>
                </div>
                <p className="text-amber-200 text-xs sm:text-sm mt-1">
                  {apiErrors.join(', ')}. Using fallback data for display.
                </p>
              </div>
            )}

            {/* Time Range Filter */}
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-3 sm:space-y-0">
              <div className="flex flex-col sm:flex-row sm:items-center space-y-2 sm:space-y-0 sm:space-x-4">
                <div className="flex items-center space-x-2">
                  <Filter className="h-4 w-4 text-blue-200" />
                  <span className="text-blue-100 text-sm font-medium">Time Range:</span>
                </div>
                <div className="flex flex-wrap gap-1 sm:gap-2">
                  {timeRanges.map((range) => (
                    <button
                      key={range.value}
                      onClick={() => setTimeRange(range)}
                      className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-all ${
                        timeRange.value === range.value
                          ? 'bg-white text-blue-600 shadow-sm'
                          : 'bg-white/10 text-blue-100 hover:bg-white/20'
                      }`}
                    >
                      {range.label}
                    </button>
                  ))}
                </div>
              </div>

              <Button
                onClick={() => setShowDetailedView(!showDetailedView)}
                className="bg-white/10 hover:bg-white/20 text-white border-white/20 mt-2 sm:mt-0"
              >
                {showDetailedView ? (
                  <EyeOff className="h-4 w-4 mr-2" />
                ) : (
                  <Eye className="h-4 w-4 mr-2" />
                )}
                {showDetailedView ? "Simple View" : "Detailed View"}
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 sm:py-8">
        {/* Event Overview */}
        <Card className="border border-gray-200/60 bg-white/80 backdrop-blur-sm shadow-lg rounded-2xl mb-6 sm:mb-8">
          <CardContent className="p-4 sm:p-6">
            <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between space-y-4 lg:space-y-0">
              <div className="space-y-3">
                <div className="flex flex-col sm:flex-row sm:items-center space-y-2 sm:space-y-0 sm:space-x-4">
                  <h2 className="text-xl sm:text-2xl font-bold text-gray-900">{event?.title}</h2>
                  {calculatedMetrics && (
                    <Badge variant={
                      calculatedMetrics.isEventFuture ? "secondary" :
                      calculatedMetrics.isEventActive ? "default" : "outline"
                    } className={
                      calculatedMetrics.isEventFuture ? "bg-yellow-100 text-yellow-800 border-yellow-200" :
                      calculatedMetrics.isEventActive ? "bg-green-100 text-green-800 border-green-200" :
                      "bg-gray-100 text-gray-800 border-gray-200"
                    }>
                      {calculatedMetrics.isEventFuture ? "Upcoming" :
                       calculatedMetrics.isEventActive ? "Live" : "Completed"}
                    </Badge>
                  )}
                </div>
                <div className="flex flex-col sm:flex-row sm:flex-wrap gap-3 sm:gap-4 text-sm text-gray-700">
                  <div className="flex items-center space-x-2">
                    <Calendar className="h-4 w-4 text-blue-600" />
                    <span>
                      {event ? new Date(event.startDate).toLocaleDateString() : ''}
                      {event?.endDate !== event?.startDate && ` - ${event ? new Date(event.endDate).toLocaleDateString() : ''}`}
                    </span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <MapPin className="h-4 w-4 text-green-600" />
                    <span>{event?.venue}</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <Ticket className="h-4 w-4 text-purple-600" />
                    <span>{event?.price ? `$${event.price}` : "Free"}</span>
                  </div>
                  {event?.category && (
                    <div className="flex items-center space-x-2">
                      <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                        {event.category}
                      </Badge>
                    </div>
                  )}
                </div>
              </div>
              <div className="flex flex-col xs:flex-row gap-3 pt-2 sm:pt-0">
                <Button
                  onClick={() => router.push(`/admin/scan`)}
                  className="bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white shadow-sm"
                >
                  <QrCode className="h-4 w-4 mr-2" />
                  Start Scanning
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Enhanced Stats Grid */}
        <div className="grid grid-cols-1 xs:grid-cols-2 lg:grid-cols-4 gap-4 sm:gap-6 mb-6 sm:mb-8">
          {/* Registration Metrics */}
          <Card className="border border-gray-200/60 bg-gradient-to-br from-blue-50 to-indigo-50 backdrop-blur-sm shadow-lg rounded-2xl">
            <CardContent className="p-4 sm:p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <p className="text-sm font-semibold text-gray-700 mb-1">Total Registrations</p>
                  <p className="text-2xl sm:text-3xl font-bold text-gray-900">
                    {registrationStats?.totalRegistrations || 0}
                  </p>
                </div>
                <div className="rounded-2xl bg-gradient-to-br from-blue-500 to-blue-600 p-2 sm:p-3 shadow-lg">
                  <Users className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-xs">
                  <span className="text-gray-700">Confirmed</span>
                  <span className="font-medium text-green-700">
                    {registrationStats?.confirmedRegistrations || 0}
                  </span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2">
                  <div 
                    className="bg-gradient-to-r from-green-500 to-emerald-600 h-2 rounded-full transition-all duration-500"
                    style={{ 
                      width: `${registrationStats && registrationStats.totalRegistrations > 0 ? 
                        (registrationStats.confirmedRegistrations / registrationStats.totalRegistrations) * 100 : 0}%` 
                    }}
                  ></div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Attendance Metrics */}
          <Card className="border border-gray-200/60 bg-gradient-to-br from-green-50 to-emerald-50 backdrop-blur-sm shadow-lg rounded-2xl">
            <CardContent className="p-4 sm:p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <p className="text-sm font-semibold text-gray-700 mb-1">Attendance</p>
                  <p className="text-2xl sm:text-3xl font-bold text-gray-900">
                    {scanStats?.checkedInTickets || 0}
                  </p>
                </div>
                <div className="rounded-2xl bg-gradient-to-br from-green-500 to-emerald-600 p-2 sm:p-3 shadow-lg">
                  <UserCheck className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-xs">
                  <span className="text-gray-700">Rate</span>
                  <span className="font-medium text-blue-700">
                    {scanStats ? Math.round(scanStats.attendanceRate) : 0}%
                  </span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2">
                  <div 
                    className="bg-gradient-to-r from-blue-500 to-cyan-600 h-2 rounded-full transition-all duration-500"
                    style={{ 
                      width: `${scanStats?.attendanceRate || 0}%` 
                    }}
                  ></div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* RSVP Verification Metrics */}
          <Card className="border border-gray-200/60 bg-gradient-to-br from-purple-50 to-pink-50 backdrop-blur-sm shadow-lg rounded-2xl">
            <CardContent className="p-4 sm:p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <p className="text-sm font-semibold text-gray-700 mb-1">RSVP Verified</p>
                  <p className="text-2xl sm:text-3xl font-bold text-gray-900">
                    {rsvpStats.rsvpVerified || 0}
                  </p>
                </div>
                <div className="rounded-2xl bg-gradient-to-br from-purple-500 to-pink-600 p-2 sm:p-3 shadow-lg">
                  <ShieldCheck className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-xs">
                  <span className="text-gray-700">Verification Rate</span>
                  <span className="font-medium text-purple-700">
                    {Math.round(rsvpStats.verificationRate)}%
                  </span>
                </div>
                <div className="w-full bg-gray-200 rounded-full h-2">
                  <div 
                    className="bg-gradient-to-r from-purple-500 to-pink-500 h-2 rounded-full transition-all duration-500"
                    style={{ 
                      width: `${rsvpStats.verificationRate || 0}%` 
                    }}
                  ></div>
                </div>
                <div className="flex justify-between text-xs text-gray-600">
                  <span>Pending: {rsvpStats.rsvpPending}</span>
                  <span>Expired: {rsvpStats.rsvpExpired}</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Quick Actions */}
          <Card className="border border-gray-200/60 bg-gradient-to-br from-orange-50 to-red-50 backdrop-blur-sm shadow-lg rounded-2xl">
            <CardContent className="p-4 sm:p-6">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <p className="text-sm font-semibold text-gray-700 mb-1">Ticket Actions</p>
                  <p className="text-lg font-bold text-gray-900">Manage Tickets</p>
                </div>
                <div className="rounded-2xl bg-gradient-to-br from-orange-500 to-red-600 p-2 sm:p-3 shadow-lg">
                  <Zap className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
                </div>
              </div>
              <div className="space-y-2">
                <Button
                  onClick={generateTicketsForRegistrations}
                  disabled={ticketActionsLoading.generate || (calculatedMetrics?.registrationsWithoutTickets || 0) <= 0}
                  variant="outline"
                  className="w-full text-xs py-1 h-8 bg-white/80 hover:bg-white border-orange-200 text-orange-700"
                  size="sm"
                >
                  {ticketActionsLoading.generate ? (
                    <RefreshCw className="h-3 w-3 mr-1 animate-spin" />
                  ) : (
                    <Sparkles className="h-3 w-3 mr-1" />
                  )}
                  Generate Tickets ({calculatedMetrics?.registrationsWithoutTickets || 0})
                </Button>
                <Button
                  onClick={sendTicketsToUsers}
                  disabled={ticketActionsLoading.send || ticketStats.pendingTickets > 0}
                  variant="outline"
                  className="w-full text-xs py-1 h-8 bg-white/80 hover:bg-white border-red-200 text-red-700"
                  size="sm"
                >
                  {ticketActionsLoading.send ? (
                    <RefreshCw className="h-3 w-3 mr-1 animate-spin" />
                  ) : (
                    <Send className="h-3 w-3 mr-1" />
                  )}
                  Send Tickets
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* RSVP Verification Section */}
        <Card className="border border-gray-200/60 bg-gradient-to-br from-indigo-50 to-purple-50 backdrop-blur-sm shadow-lg rounded-2xl mb-6 sm:mb-8">
          <CardHeader className="pb-4">
            <CardTitle className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Link className="h-6 w-6 text-indigo-600" />
                <span>RSVP Verification System</span>
              </div>
              <Badge variant="outline" className="bg-indigo-50 text-indigo-700 border-indigo-200">
                {rsvpStats.rsvpPending} Pending
              </Badge>
            </CardTitle>
            <CardDescription className="text-gray-700">
              Send verification links and track RSVP confirmations with detailed analytics
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <h4 className="font-medium text-gray-900">Verification Analytics</h4>
                <div className="grid grid-cols-2 gap-4">
                  <div className="text-center p-3 bg-white rounded-lg border border-indigo-100">
                    <div className="text-2xl font-bold text-indigo-600">{rsvpStats.rsvpSent}</div>
                    <div className="text-xs text-indigo-700">RSVP Sent</div>
                  </div>
                  <div className="text-center p-3 bg-white rounded-lg border border-green-100">
                    <div className="text-2xl font-bold text-green-600">{rsvpStats.rsvpVerified}</div>
                    <div className="text-xs text-green-700">Verified</div>
                  </div>
                  <div className="text-center p-3 bg-white rounded-lg border border-yellow-100">
                    <div className="text-2xl font-bold text-yellow-600">{rsvpStats.rsvpPending}</div>
                    <div className="text-xs text-yellow-700">Pending</div>
                  </div>
                  <div className="text-center p-3 bg-white rounded-lg border border-red-100">
                    <div className="text-2xl font-bold text-red-600">{rsvpStats.rsvpExpired}</div>
                    <div className="text-xs text-red-700">Expired</div>
                  </div>
                </div>
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-gray-700">Verification Rate</span>
                    <span className="font-medium text-gray-900">{Math.round(rsvpStats.verificationRate)}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2">
                    <div 
                      className="bg-gradient-to-r from-indigo-500 to-purple-600 h-2 rounded-full transition-all duration-500"
                      style={{ width: `${rsvpStats.verificationRate}%` }}
                    ></div>
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <h4 className="font-medium text-gray-900">Quick Actions</h4>
                <div className="space-y-3">
                  <Button
                    onClick={sendRSVPWithVerification}
                    disabled={rsvpVerificationLoading}
                    className="w-full bg-indigo-600 hover:bg-indigo-700 text-white"
                  >
                    {rsvpVerificationLoading ? (
                      <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    ) : (
                      <Send className="h-4 w-4 mr-2" />
                    )}
                    Send RSVP Verification Links
                  </Button>
                  
                  <Button
                    onClick={() => exportAnalyticsData('rsvp')}
                    variant="outline"
                    className="w-full border-indigo-200 text-indigo-700 hover:bg-indigo-50"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Export RSVP Analytics
                  </Button>

                  <div className="text-xs text-gray-600 space-y-1">
                    <p>• Links expire in 7 days</p>
                    <p>• Automatic ticket generation upon verification</p>
                    <p>• Real-time analytics tracking</p>
                  </div>
                </div>
              </div>
            </div>

            {/* Verification Progress */}
            <div className="border-t pt-4">
              <h4 className="font-medium text-gray-900 mb-3">Verification Progress</h4>
              <div className="space-y-3">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">Total Registrations</span>
                  <span className="font-medium text-gray-900">{rsvpStats.totalRegistrations}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">RSVP Links Sent</span>
                  <span className="font-medium text-gray-900">{rsvpStats.rsvpSent} ({Math.round(rsvpStats.sentRate)}%)</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">Successfully Verified</span>
                  <span className="font-medium text-green-700">{rsvpStats.rsvpVerified} ({Math.round(rsvpStats.verificationRate)}%)</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">Awaiting Response</span>
                  <span className="font-medium text-yellow-700">{rsvpStats.rsvpPending}</span>
                </div>
                <div className="flex items-center justify-between text-sm">
                  <span className="text-gray-700">Links Expired</span>
                  <span className="font-medium text-red-700">{rsvpStats.rsvpExpired}</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Mass Communication Section */}
        <Card className="border border-gray-200/60 bg-gradient-to-br from-teal-50 to-cyan-50 backdrop-blur-sm shadow-lg rounded-2xl mb-6 sm:mb-8">
          <CardContent className="p-4 sm:p-6">
            <div className="flex items-center justify-between mb-4">
              <div>
                <p className="text-sm font-semibold text-gray-700 mb-1">Mass Communication</p>
                <p className="text-lg font-bold text-gray-900">Send Notifications & RSVP</p>
              </div>
              <div className="rounded-2xl bg-gradient-to-br from-teal-500 to-cyan-600 p-2 sm:p-3 shadow-lg">
                <Send className="h-5 w-5 sm:h-6 sm:w-6 text-white" />
              </div>
            </div>
            <div className="space-y-3">
              <Button
                onClick={sendEventNotification}
                disabled={notificationLoading}
                variant="outline"
                className="w-full text-xs py-2 h-9 bg-white/80 hover:bg-white border-teal-200 text-teal-700"
                size="sm"
              >
                {notificationLoading ? (
                  <RefreshCw className="h-3 w-3 mr-2 animate-spin" />
                ) : (
                  <Bell className="h-3 w-3 mr-2" />
                )}
                Notify All Users About Event
              </Button>
              <Button
                onClick={sendRSVPToRegisteredStudents}
                disabled={rsvpLoading}
                variant="outline"
                className="w-full text-xs py-2 h-9 bg-white/80 hover:bg-white border-cyan-200 text-cyan-700"
                size="sm"
              >
                {rsvpLoading ? (
                  <RefreshCw className="h-3 w-3 mr-2 animate-spin" />
                ) : (
                  <MessageCircle className="h-3 w-3 mr-2" />
                )}
                Send RSVP to Registered Students ({tickets.filter(t => t.status === 'active').length})
              </Button>
              <div className="grid grid-cols-2 gap-2 text-xs text-gray-700 pt-2">
                <div className="flex items-center">
                  <Users className="h-3 w-3 mr-1 text-teal-600" />
                  <span>All Users: Notification</span>
                </div>
                <div className="flex items-center">
                  <GraduationCap className="h-3 w-3 mr-1 text-cyan-600" />
                  <span>Registered: RSVP</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Ticket Management Section */}
        <Card className="border border-gray-200/60 bg-white/80 backdrop-blur-sm shadow-lg rounded-2xl mb-6 sm:mb-8">
          <CardHeader className="pb-4">
            <CardTitle className="flex items-center justify-between">
              <div className="flex items-center space-x-2">
                <Settings className="h-6 w-6 text-blue-600" />
                <span>Ticket Management</span>
              </div>
              <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                {ticketStats.pendingTickets} Pending
              </Badge>
            </CardTitle>
            <CardDescription className="text-gray-700">
              Configure ticket generation and distribution settings for this event
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Ticket Settings */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <h4 className="font-medium text-gray-900">Ticket Generation</h4>
                <div className="space-y-4">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="auto-generate" className="flex items-center space-x-2 text-gray-700">
                      <Sparkles className="h-4 w-4 text-purple-600" />
                      <span>Auto-generate tickets</span>
                    </Label>
                    <Switch
                      id="auto-generate"
                      checked={ticketSettings.autoGenerate}
                      onCheckedChange={(checked: boolean) => handleTicketSettingChange('autoGenerate', checked)}
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <Label htmlFor="send-email" className="flex items-center space-x-2 text-gray-700">
                      <Mail className="h-4 w-4 text-green-600" />
                      <span>Auto-send tickets via email</span>
                    </Label>
                    <Switch
                      id="send-email"
                      checked={ticketSettings.sendEmail}
                      onCheckedChange={(checked: boolean) => handleTicketSettingChange('sendEmail', checked)}
                    />
                  </div>
                  <div className="flex items-center justify-between">
                    <Label htmlFor="manual-approval" className="flex items-center space-x-2 text-gray-700">
                      <Shield className="h-4 w-4 text-orange-600" />
                      <span>Require manual approval</span>
                    </Label>
                    <Switch
                      id="manual-approval"
                      checked={ticketSettings.manualApproval}
                      onCheckedChange={(checked: boolean) => handleTicketSettingChange('manualApproval', checked)}
                    />
                  </div>
                </div>
              </div>

              <div className="space-y-4">
                <h4 className="font-medium text-gray-900">Quick Actions</h4>
                <div className="space-y-3">
                  <Button
                    onClick={approvePendingTickets}
                    disabled={ticketActionsLoading.approve || ticketStats.pendingTickets === 0}
                    className="w-full"
                    variant="outline"
                  >
                    {ticketActionsLoading.approve ? (
                      <RefreshCw className="h-4 w-4 mr-2 animate-spin" />
                    ) : (
                      <CheckCircle className="h-4 w-4 mr-2" />
                    )}
                    Approve Pending Tickets ({ticketStats.pendingTickets})
                  </Button>
                  
                  <Button
                    onClick={() => exportAnalyticsData('tickets')}
                    className="w-full"
                    variant="outline"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Export Ticket Data
                  </Button>

                  <div className="grid grid-cols-2 gap-2 text-xs text-gray-700">
                    <div className="flex items-center">
                      <MailCheck className="h-3 w-3 mr-1 text-green-600" />
                      <span>Sent: {ticketStats.sentTickets}</span>
                    </div>
                    <div className="flex items-center">
                      <MailWarning className="h-3 w-3 mr-1 text-orange-600" />
                      <span>Pending: {ticketStats.pendingTickets}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Ticket Status Summary */}
            <div className="border-t pt-4">
              <h4 className="font-medium text-gray-900 mb-3">Ticket Status Summary</h4>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="text-center p-3 bg-blue-50 rounded-lg border border-blue-100">
                  <div className="text-2xl font-bold text-blue-700">{ticketStats.totalTickets}</div>
                  <div className="text-xs text-blue-700">Total Tickets</div>
                </div>
                <div className="text-center p-3 bg-green-50 rounded-lg border border-green-100">
                  <div className="text-2xl font-bold text-green-700">{ticketStats.activeTickets}</div>
                  <div className="text-xs text-green-700">Active</div>
                </div>
                <div className="text-center p-3 bg-orange-50 rounded-lg border border-orange-100">
                  <div className="text-2xl font-bold text-orange-700">{ticketStats.pendingTickets}</div>
                  <div className="text-xs text-orange-700">Pending</div>
                </div>
                <div className="text-center p-3 bg-purple-50 rounded-lg border border-purple-100">
                  <div className="text-2xl font-bold text-purple-700">{ticketStats.sentTickets}</div>
                  <div className="text-xs text-purple-700">Sent</div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Analytics Content */}
        <div className="grid grid-cols-1 xl:grid-cols-3 gap-6 sm:gap-8 mb-8">
          {/* Main Content - Registration List */}
          <div className="xl:col-span-2">
            <Card className="border border-gray-200/60 bg-white/80 backdrop-blur-sm shadow-lg rounded-2xl">
              <CardHeader className="pb-4">
                <CardTitle className="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-2 sm:space-y-0">
                  <div className="flex items-center space-x-2">
                    <FileText className="h-6 w-6 text-indigo-600" />
                    <span className="text-lg sm:text-xl">Registration List</span>
                  </div>
                  <div className="flex flex-col sm:flex-row sm:items-center gap-2">
                    <Badge variant="outline" className="bg-indigo-50 text-indigo-700 border-indigo-200 w-fit">
                      {filteredRegistrations.length} registrations
                    </Badge>
                    <Badge variant="outline" className="bg-green-50 text-green-700 border-green-200 w-fit">
                      RSVP Verified: {rsvpStats.rsvpVerified}
                    </Badge>
                  </div>
                </CardTitle>
                <CardDescription className="text-gray-700">
                  Complete list of all event registrations with check-in/check-out status and RSVP verification tracking
                </CardDescription>
              </CardHeader>
              <CardContent>
                {/* Search and Filter Bar */}
                <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 mb-6">
                  <div className="flex-1 relative">
                    <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-500 h-4 w-4" />
                    <Input
                      placeholder="Search by name, email, institution..."
                      value={searchTerm}
                      onChange={(e) => setSearchTerm(e.target.value)}
                      className="pl-10"
                    />
                  </div>
                  <div className="flex gap-2">
                    <Button
                      variant={registrationFilter === 'all' ? "default" : "outline"}
                      onClick={() => setRegistrationFilter('all')}
                      size="sm"
                      className="flex-1 sm:flex-none"
                    >
                      All
                    </Button>
                    <Button
                      variant={registrationFilter === 'confirmed' ? "default" : "outline"}
                      onClick={() => setRegistrationFilter('confirmed')}
                      size="sm"
                      className="flex-1 sm:flex-none"
                    >
                      Confirmed
                    </Button>
                    <Button
                      variant={registrationFilter === 'pending' ? "default" : "outline"}
                      onClick={() => setRegistrationFilter('pending')}
                      size="sm"
                      className="flex-1 sm:flex-none"
                    >
                      Pending
                    </Button>
                  </div>
                  <Button
                    onClick={() => exportAnalyticsData('registration-list')}
                    variant="outline"
                    size="sm"
                    className="whitespace-nowrap"
                  >
                    <Download className="h-4 w-4 mr-2" />
                    Export CSV
                  </Button>
                </div>

                {/* Registration Table */}
                <div className="border border-gray-200 rounded-lg overflow-hidden">
                  <div className="overflow-x-auto">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50 border-b border-gray-200">
                        <tr>
                          <th className="text-left p-3 font-medium text-gray-700">Attendee</th>
                          <th className="text-left p-3 font-medium text-gray-700 hidden sm:table-cell">Contact</th>
                          <th className="text-left p-3 font-medium text-gray-700 hidden lg:table-cell">Education</th>
                          <th className="text-left p-3 font-medium text-gray-700">Reg Date</th>
                          <th className="text-left p-3 font-medium text-gray-700">Status</th>
                          <th className="text-left p-3 font-medium text-gray-700">Ticket</th>
                          <th className="text-left p-3 font-medium text-gray-700">RSVP Status</th>
                          <th className="text-left p-3 font-medium text-gray-700">Check-in/out</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-200">
                        {filteredRegistrations.length > 0 ? (
                          filteredRegistrations.map((registration) => {
                            const scanData = getRegistrationScanData(registration);
                            const ticketData = getRegistrationTicketData(registration);
                            const rsvpStatus = getRSVPVerificationStatus(registration);
                            
                            const ticketStatus = ticketData ? 
                              ticketData.status.charAt(0).toUpperCase() + ticketData.status.slice(1) : 
                              'Not Generated';

                            const isCheckedIn = scanData?.checkedIn && !scanData.checkOutTime;
                            const isCheckedOut = scanData?.checkOutTime;
                            const isPresent = isCheckedIn && !isCheckedOut;

                            return (
                              <tr key={registration._id} className="hover:bg-gray-50 transition-colors">
                                <td className="p-3">
                                  <div className="flex items-center space-x-3">
                                    <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white text-xs font-medium">
                                      {registration.userId.firstName[0]}{registration.userId.lastName[0]}
                                    </div>
                                    <div className="min-w-0">
                                      <p className="font-medium text-gray-900 truncate">
                                        {registration.userId.firstName} {registration.userId.lastName}
                                      </p>
                                      <p className="text-gray-600 text-xs truncate sm:hidden">
                                        {registration.userId.email}
                                      </p>
                                    </div>
                                  </div>
                                </td>
                                <td className="p-3 hidden sm:table-cell">
                                  <div className="space-y-1">
                                    <p className="text-gray-900 flex items-center">
                                      <Mail className="h-3 w-3 mr-1 text-gray-500" />
                                      <span className="truncate">{registration.userId.email}</span>
                                    </p>
                                    {registration.source && (
                                      <Badge variant="outline" className="text-xs bg-gray-50 text-gray-700">
                                        {registration.source}
                                      </Badge>
                                    )}
                                  </div>
                                </td>
                                <td className="p-3 hidden lg:table-cell">
                                  <div className="space-y-1">
                                    {registration.userId.profile?.institution && (
                                      <p className="text-gray-700 flex items-center text-xs">
                                        <Building className="h-3 w-3 mr-1" />
                                        <span className="truncate">{registration.userId.profile.institution}</span>
                                      </p>
                                    )}
                                    {registration.userId.profile?.course && (
                                      <p className="text-gray-700 flex items-center text-xs">
                                        <BookOpen className="h-3 w-3 mr-1" />
                                        <span className="truncate">{registration.userId.profile.course}</span>
                                      </p>
                                    )}
                                  </div>
                                </td>
                                <td className="p-3 text-gray-700">
                                  <div className="flex items-center">
                                    <CalendarDays className="h-3 w-3 mr-1" />
                                    <span className="text-xs sm:text-sm">{new Date(registration.createdAt).toLocaleDateString()}</span>
                                  </div>
                                </td>
                                <td className="p-3">
                                  <Badge
                                    variant="outline"
                                    className={
                                      registration.status === 'confirmed' 
                                        ? "bg-green-50 text-green-700 border-green-200"
                                        : "bg-yellow-50 text-yellow-700 border-yellow-200"
                                    }
                                  >
                                    {registration.status === 'confirmed' ? (
                                      <CheckCircle className="h-3 w-3 mr-1" />
                                    ) : (
                                      <Clock className="h-3 w-3 mr-1" />
                                    )}
                                    <span className="hidden xs:inline">
                                      {registration.status.charAt(0).toUpperCase() + registration.status.slice(1)}
                                    </span>
                                  </Badge>
                                </td>
                                <td className="p-3">
                                  <div className="space-y-1">
                                    <Badge
                                      variant="outline"
                                      className={
                                        ticketStatus === 'Active' 
                                          ? "bg-green-50 text-green-700 border-green-200" :
                                        ticketStatus === 'Pending'
                                          ? "bg-yellow-50 text-yellow-700 border-yellow-200" :
                                        ticketStatus === 'Not Generated'
                                          ? "bg-gray-50 text-gray-700 border-gray-200" :
                                          "bg-red-50 text-red-700 border-red-200"
                                      }
                                    >
                                      {ticketStatus === 'Active' ? (
                                        <CheckCircle className="h-3 w-3 mr-1" />
                                      ) : ticketStatus === 'Pending' ? (
                                        <Clock className="h-3 w-3 mr-1" />
                                      ) : ticketStatus === 'Not Generated' ? (
                                        <UserX className="h-3 w-3 mr-1" />
                                      ) : (
                                        <AlertCircle className="h-3 w-3 mr-1" />
                                      )}
                                      <span className="hidden xs:inline">{ticketStatus}</span>
                                    </Badge>
                                    {ticketData && (
                                      <div className="text-xs text-gray-600 space-y-0.5">
                                        {ticketData.emailSent && (
                                          <div className="flex items-center">
                                            <MailCheck className="h-2.5 w-2.5 mr-1 text-green-600" />
                                            <span>Email Sent</span>
                                          </div>
                                        )}
                                        {ticketData.autoGenerated && (
                                          <div className="text-gray-500">
                                            Auto-generated
                                          </div>
                                        )}
                                      </div>
                                    )}
                                  </div>
                                </td>
                                <td className="p-3">
                                  <div className="space-y-1">
                                    {rsvpStatus === 'verified' && (
                                      <Badge className="bg-green-100 text-green-800 border-green-200 text-xs">
                                        <ShieldCheck className="h-3 w-3 mr-1" />
                                        Verified
                                        {registration.rsvpVerifiedAt && (
                                          <span className="ml-1">
                                            {new Date(registration.rsvpVerifiedAt).toLocaleDateString()}
                                          </span>
                                        )}
                                      </Badge>
                                    )}
                                    {rsvpStatus === 'pending' && (
                                      <div className="space-y-1">
                                        <Badge className="bg-yellow-100 text-yellow-800 border-yellow-200 text-xs">
                                          <Clock className="h-3 w-3 mr-1" />
                                          Pending Verification
                                        </Badge>
                                        <Button
                                          onClick={() => resendVerificationLink(registration._id)}
                                          variant="ghost"
                                          size="sm"
                                          className="h-6 text-xs text-blue-600 hover:text-blue-700 hover:bg-blue-50"
                                        >
                                          <RotateCcw className="h-3 w-3 mr-1" />
                                          Resend
                                        </Button>
                                      </div>
                                    )}
                                    {rsvpStatus === 'expired' && (
                                      <Badge className="bg-red-100 text-red-800 border-red-200 text-xs">
                                        <AlertCircle className="h-3 w-3 mr-1" />
                                        Link Expired
                                      </Badge>
                                    )}
                                    {rsvpStatus === 'not-sent' && (
                                      <Badge variant="outline" className="text-xs bg-gray-50 text-gray-700 border-gray-200">
                                        <Mail className="h-3 w-3 mr-1" />
                                        Not Sent
                                      </Badge>
                                    )}
                                  </div>
                                </td>
                                <td className="p-3">
                                  <div className="space-y-1 min-w-[120px]">
                                    {isPresent ? (
                                      <Badge className="bg-green-100 text-green-800 border-green-200 text-xs">
                                        <CheckCircle className="h-3 w-3 mr-1" />
                                        Present
                                      </Badge>
                                    ) : isCheckedOut ? (
                                      <Badge className="bg-blue-100 text-blue-800 border-blue-200 text-xs">
                                        <LogOut className="h-3 w-3 mr-1" />
                                        Checked Out
                                      </Badge>
                                    ) : scanData?.checkedIn ? (
                                      <Badge className="bg-yellow-100 text-yellow-800 border-yellow-200 text-xs">
                                        <LogIn className="h-3 w-3 mr-1" />
                                        Checked In
                                      </Badge>
                                    ) : (
                                      <Badge variant="outline" className="text-xs text-gray-700">
                                        Not Checked In
                                      </Badge>
                                    )}
                                    
                                    {scanData?.checkInTime && (
                                      <p className="text-xs text-gray-600">
                                        In: {new Date(scanData.checkInTime).toLocaleTimeString()}
                                      </p>
                                    )}
                                    {scanData?.checkOutTime && (
                                      <p className="text-xs text-gray-600">
                                        Out: {new Date(scanData.checkOutTime).toLocaleTimeString()}
                                      </p>
                                    )}
                                    {scanData?.scanMethod && (
                                      <p className="text-xs text-gray-500">
                                        {scanData.scanMethod === 'qr' ? 'QR Scan' : 'Manual'}
                                      </p>
                                    )}
                                  </div>
                                </td>
                              </tr>
                            );
                          })
                        ) : (
                          <tr>
                            <td colSpan={8} className="p-8 text-center text-gray-600">
                              <UserX className="h-12 w-12 mx-auto mb-4 text-gray-400" />
                              <p>No registrations found</p>
                              {searchTerm && (
                                <p className="text-sm mt-1">Try adjusting your search terms</p>
                              )}
                            </td>
                          </tr>
                        )}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Summary */}
                <div className="flex flex-col sm:flex-row sm:justify-between sm:items-center mt-4 text-sm text-gray-700 space-y-2 sm:space-y-0">
                  <span>
                    Showing {filteredRegistrations.length} of {registrations.length} registrations
                  </span>
                  <div className="flex gap-4">
                    <span className="flex items-center">
                      <div className="w-2 h-2 bg-green-500 rounded-full mr-1"></div>
                      Confirmed: {registrations.filter(r => r.status === 'confirmed').length}
                    </span>
                    <span className="flex items-center">
                      <div className="w-2 h-2 bg-indigo-500 rounded-full mr-1"></div>
                      RSVP Verified: {registrations.filter(r => r.rsvpVerified).length}
                    </span>
                    <span className="flex items-center">
                      <div className="w-2 h-2 bg-yellow-500 rounded-full mr-1"></div>
                      Pending: {registrations.filter(r => r.status === 'pending').length}
                    </span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar */}
          <div className="space-y-6 sm:space-y-8">
            {/* Recent Activity */}
            <Card className="border border-gray-200/60 bg-white/80 backdrop-blur-sm shadow-lg rounded-2xl">
              <CardHeader className="pb-4">
                <CardTitle className="flex flex-col sm:flex-row sm:items-center sm:justify-between space-y-2 sm:space-y-0">
                  <div className="flex items-center space-x-2">
                    <Activity className="h-6 w-6 text-purple-600" />
                    <span>Recent Activity</span>
                  </div>
                  <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200 w-fit">
                    {recentScans.length}
                  </Badge>
                </CardTitle>
                <CardDescription className="text-gray-700">
                  Latest check-ins and check-outs
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4 max-h-96 overflow-y-auto">
                  {recentScans.length > 0 ? (
                    recentScans.slice(0, 10).map((scan) => (
                      <div
                        key={scan._id}
                        className="flex items-center justify-between p-3 rounded-lg border border-gray-200 bg-white hover:bg-gray-50 transition-colors"
                      >
                        <div className="flex items-center space-x-3 min-w-0 flex-1">
                          <div className={`w-2.5 h-2.5 rounded-full flex-shrink-0 ${
                            scan.checkedIn && !scan.checkOutTime ? 'bg-green-500' :
                            scan.checkOutTime ? 'bg-blue-500' : 'bg-gray-300'
                          }`}></div>
                          <div className="min-w-0 flex-1">
                            <p className="font-medium text-gray-900 text-sm truncate">
                              {scan.userId ? `${scan.userId.firstName} ${scan.userId.lastName}` : 'Unknown User'}
                            </p>
                            <p className="text-gray-600 text-xs truncate">
                              {scan.userId?.email || 'No email'}
                            </p>
                            {scan.checkInTime && (
                              <p className="text-gray-500 text-xs flex items-center mt-1">
                                <Clock className="h-3 w-3 mr-1" />
                                {new Date(scan.checkInTime).toLocaleTimeString()}
                              </p>
                            )}
                          </div>
                        </div>
                        <Badge
                          variant="outline"
                          className={
                            scan.checkedIn && !scan.checkOutTime ? "bg-green-50 text-green-700 border-green-200 text-xs flex-shrink-0" :
                            scan.checkOutTime ? "bg-blue-50 text-blue-700 border-blue-200 text-xs flex-shrink-0" : 
                            "bg-gray-50 text-gray-700 border-gray-200 text-xs flex-shrink-0"
                          }
                        >
                          {scan.checkedIn && !scan.checkOutTime ? "In" :
                           scan.checkOutTime ? "Out" : "Pending"}
                        </Badge>
                      </div>
                    ))
                  ) : (
                    <div className="text-center py-8">
                      <UserX className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                      <p className="text-gray-600">No recent activity</p>
                      <p className="text-gray-500 text-sm mt-1">
                        {apiErrors.some(e => e.includes('Recent scans')) 
                          ? "Scan data temporarily unavailable" 
                          : "Activity will appear here"
                        }
                      </p>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Event Status */}
            <Card className="border border-gray-200/60 bg-gradient-to-br from-slate-50 to-gray-100 backdrop-blur-sm shadow-lg rounded-2xl">
              <CardHeader className="pb-4">
                <CardTitle className="flex items-center space-x-2">
                  <BarChart3 className="h-6 w-6 text-gray-700" />
                  <span>Event Status</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                {calculatedMetrics && (
                  <div className="space-y-3">
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-gray-700">Event Status</span>
                      <Badge variant={
                        calculatedMetrics.isEventFuture ? "secondary" :
                        calculatedMetrics.isEventActive ? "default" : "outline"
                      } className="text-xs">
                        {calculatedMetrics.isEventFuture ? "Upcoming" :
                         calculatedMetrics.isEventActive ? "Live" : "Completed"}
                      </Badge>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-gray-700">Attendance Rate</span>
                      <span className="font-medium text-gray-900">
                        {scanStats ? Math.round(scanStats.attendanceRate) : 0}%
                      </span>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-gray-700">RSVP Verification Rate</span>
                      <span className="font-medium text-gray-900">
                        {calculatedMetrics.rsvpVerificationRate ? Math.round(calculatedMetrics.rsvpVerificationRate) : 0}%
                      </span>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-gray-700">Capacity Used</span>
                      <span className="font-medium text-gray-900">
                        {calculatedMetrics.attendanceFillRate ? Math.round(calculatedMetrics.attendanceFillRate) : 0}%
                      </span>
                    </div>
                    <div className="flex justify-between items-center text-sm">
                      <span className="text-gray-700">Remaining Capacity</span>
                      <span className="font-medium text-gray-900">
                        {calculatedMetrics.remainingCapacity || 0}
                      </span>
                    </div>
                  </div>
                )}
                
                <div className="pt-4 border-t border-gray-200">
                  <div className="flex justify-between text-xs text-gray-600">
                    <span>Last Updated</span>
                    <span>{new Date().toLocaleTimeString()}</span>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Setup Instructions for Missing Endpoints */}
        {apiErrors.length > 0 && (
          <Card className="border border-amber-200 bg-amber-50/80 backdrop-blur-sm rounded-2xl">
            <CardContent className="p-6">
              <div className="flex items-start space-x-4">
                <div className="p-2 bg-amber-100 rounded-lg">
                  <AlertCircle className="h-6 w-6 text-amber-600" />
                </div>
                <div className="flex-1">
                  <h3 className="font-semibold text-amber-900 mb-2">Analytics Setup Required</h3>
                  <p className="text-amber-800 text-sm mb-3">
                    Some analytics features require backend endpoints that are not currently available.
                    The page is currently showing basic data with fallback values.
                  </p>
                  <div className="text-amber-700 text-xs space-y-1">
                    <p>• Registration stats endpoint: <code>/api/registration/responses/:id/stats</code></p>
                    <p>• Recent scans endpoint: <code>/api/tickets/event/:id/recent-scans</code></p>
                    <p>• RSVP analytics endpoint: <code>/api/events/:id/rsvp-analytics</code></p>
                    <p>• Advanced analytics: <code>/api/tickets/event/:id/stats</code> with time ranges</p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}